<?php
    $lang = array(
        "CHEESE PIZZA" => "พิซซ่าหน้าชีส",
        "DOUBLE PEPPERONI" => "ดับเบิ้ลเปปเปอโรนี",
        "HAM&CRAB STICKS" => "แฮมและปูอัด",
        "MEAT DELUXE" => "มีทเดอลุกซ์",
        "TOM YUM KUNG" => "ต้มยำกุ้ง",
        "SEAFOOD DELUXE" => "ซีฟู้ดเดอลุกซ์",
        "SIZE" => "ขนาด",
        "CRUST" => "ขอบ",
        "PAN CRUST" => "ขอบหนานุ่ม",
        "CRISPY THIN" => "ขอบบางกรอบ",
        "CHEESE CRUST" => "ขอบชีส",
        "SAUSAGE&CHEESE CRUST" => "ขอบไส้กรอกชีส",
        "CHEESE" => "ชีส",
        "HAM" => "แฮม",
        "PEPPERONI" => "เปปเปอโรนี",
        "ADD" => "เพิ่มสินค้าในตะกร้า",
        "CLEAR" => "ล้างข้อมูล",
        "ORDER SUMMARY" => "สรุปคำสั่งซื้อ",
        "Items in the cart" => "สินค้าในตะกร้า",
        "SORRY" => "ขออภัย ขณะนี้ไม่มีสินค้าในตะกร้า",
        "pieces" => "ชิ้น",
        "Total price" => "ราคารวม",
        "PAYMENT" => "จ่ายเงิน",
        "TAP TO START" => "แตะหน้าจอเพื่อเริ่มสั่งซื้อ",
        "" => "",
        "" => "",
        "" => "",
        "" => ""
    );
?>