<?php
    $lang = array(
        "CHEESE PIZZA" => "CHEESE PIZZA",
        "DOUBLE PEPPERONI" => "DOUBLE PEPPERONI",
        "HAM&CRAB STICKS" => "HAM&CRAB STICKS",
        "MEAT DELUXE" => "MEAT DELUXE",
        "TOM YUM KUNG" => "TOM YUM KUNG",
        "SEAFOOD DELUXE" => "SEAFOOD DELUXE",
        "SIZE" => "SIZE",
        "CRUST" => "CRUST",
        "PAN CRUST" => "PAN CRUST",
        "CRISPY THIN" => "CRISPY THIN",
        "CHEESE CRUST" => "CHEESE CRUST",
        "SAUSAGE&CHEESE CRUST" => "SAUSAGE&CHEESE CRUST",
        "CHEESE" => "CHEESE",
        "HAM" => "HAM",
        "PEPPERONI" => "PEPPERONI",
        "ADD" => "ADD",
        "CLEAR" => "CLEAR",
        "ORDER SUMMARY" => "ORDER SUMMARY",
        "" => "",
        "" => "",
        "" => "",
        "" => "",
        "" => "",
        "" => "",
        "" => "",
        "" => "",
        "" => "",
        "" => ""
    );
?>